### ISSUE TITLE
optional crates should resolve as features, but zed-cargotom reports an error

### ISSUE THREAD

**Issue by kurtbuilds** [frederik-uni/zed-cargotom#5]
<img width="611" alt="image" src="https://github.com/user-attachments/assets/7bceba7a-a3aa-4dc7-9f94-64343afdaea6">
I'm depending on this crate `sqlmo` (it's my crate, but not relevant). `zed-cargotom` reports `tracing` as not being a feature. However, it is a feature because of the optional dependency on `tracing` in crate `sqlmo`.

Expected behavior:
optional dependencies are valid as feature flags for crates.

**Comment by frederik-uni** [comment]
https://github.com/frederik-uni/crates.io-index-minfied/commit/787f27b0cdbfdca6f46c38c8afd8f177f65bbdd9
