### ISSUE TITLE
Don't suggest pre-release versions

### ISSUE THREAD

**Issue by kurtbuilds** [frederik-uni/zed-cargotom#6]
<img width="495" alt="image" src="https://github.com/user-attachments/assets/b47bae3d-2a9c-466e-909b-625c7246cf95">

`sha2` is currently on 0.10, with a prerelease 0.11.0-pre.4 available.

`zed-cargotom` should not warn or suggest prerelease versions.

**Comment by frederik-uni** [comment]
it should be fixed now. there is a stable: bool in the config, but it only applied to the online api. it should work for the offline mode too
